/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#fbf9f8",
        "on-surface": "#1b1c1c",
        "surface-dim": "#dcd9d9",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#400106",
        "tertiary-fixed": "#acf1d5",
        "status-resolved": "#2E7D32",
        "on-secondary": "#ffffff",
        "status-emergency": "#C62828",
        "primary-container": "#7b2c2c",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "surface-variant": "#e4e2e1",
        "on-error-container": "#93000a",
        "ai-accent": "#E3F2FD",
        "outline-variant": "#dbc1bf",
        "on-background": "#1b1c1c",
        "inverse-surface": "#303030",
        "surface-container-highest": "#e4e2e1",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#00513d",
        "inverse-primary": "#ffb3af",
        "surface-container-low": "#f6f3f2",
        "primary-fixed-dim": "#ffb3af",
        "surface-bright": "#fbf9f8",
        "tertiary-fixed-dim": "#91d4ba",
        "on-tertiary-fixed": "#002117",
        "secondary-container": "#ff668e",
        "inverse-on-surface": "#f3f0f0",
        "surface": "#fbf9f8",
        "secondary-fixed-dim": "#ffb1c0",
        "on-primary-fixed-variant": "#7b2c2c",
        "surface-container-high": "#eae8e7",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#554241",
        "on-secondary-fixed": "#3f0016",
        "on-primary-container": "#ff9894",
        "on-error": "#ffffff",
        "background-alt": "#F4F4F4",
        "surface-tint": "#9a4342",
        "primary-fixed": "#ffdad8",
        "on-tertiary-container": "#80c2a9",
        "ai-stroke": "#2196F3",
        "surface-container": "#f0eded",
        "on-secondary-container": "#6b002b",
        "primary": "#5d1618",
        "secondary": "#af2853",
        "status-pending": "#FF8F00",
        "secondary-fixed": "#ffd9df",
        "outline": "#887271",
        "tertiary": "#003829",
        "on-secondary-fixed-variant": "#8e083c",
        "tertiary-container": "#00513d"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xs": "8px",
        "margin-mobile": "16px",
        "gutter": "20px",
        "base": "4px",
        "margin-desktop": "auto",
        "sm": "16px",
        "lg": "40px",
        "xl": "64px",
        "md": "24px",
        "max-width": "1280px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
